### ISSUE TITLE
Install a package if 2 other packages are installed

### ISSUE THREAD

**Issue by sminnee** [silverstripe/recipe-plugin#8]
If you have installed both userforms and elemental, then you will likely want to install `dnadesign/silverstripe-elemental-userforms`. It would be nice to automated this in a recipe.

Suggested syntax is a "extra.require-optional" config option:

```json
{
    "name": "silverstripe/recipe-content-blocks",
    "type": "silverstripe-recipe",
    "require": {
        "silverstripe/elemental-blocks": "1.0.x-dev"
    },
    "extra": {
        "require-optional": {
          "dnadesign/silverstripe-elemental-userforms:^1": {
            "if-installed": [ "silverstripe/userforms:*" ],
           }
        }
    }
}
```

A  few notes:

 * the keys are `package:constraint` pairs, this would let you optionally install different versions based on different conditions
 * The `if-installed` checks are `package:constraint` pairs for different reasons
 * `if-not-installed` would be another option.
 * As well as package constraints you could use php & php-extension checks as composer currently does. This might be an add-on for later.
 * I'm not sure if there are other options that could be added.

Implementation implications:

 * It would require that there's a couple of passes over the dependency resolver. This, btw, is one reason why composer have never added such functionality themselves.

**Comment by maxime-rainville** [comment]
Aside from a combination of the content-blocks package with some other packages, are we going to have many of those situation?

I'm wondering how/if we should handle the reverse case? e.g.: You've got `recipe-content-blocks` and `silverstripe/userforms` installed, but explicitly don't want `dnadesign/content-userforms`.

**Comment by stevie-mayhew** [comment]
I don't like that this could end up installing things that I may not want, as Max suggested. I'd prefer if we made that kind of setup more explicit in documentation and aggressively using "suggests"?

**Comment by sminnee** [comment]
Fair enough maybe we scrap it?

**Comment by maxime-rainville** [comment]
I guess we do have a fair bit of those edge cases where if some module is present, additional functionality become available.

We have two general approaches we can take:
* either we include the additional functionality in some integration module
* or we include the additional functionality in the "less-generic" module with some judicious use of `class_exists` statements

In the abstract, I would probably favour the "integration module" route to avoid coupling modules.

However, I think in the specific case of Elemental, this module is becoming so ubiquitous that it would make sense to use the "class_exists" approach for elemental integrations.
